const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const context = { window: {} };
vm.createContext(context);
vm.runInContext(fs.readFileSync('docs/programs.js', 'utf8'), context);
const P = context.window.ProgramRegistry;
const labels = ['חבר', 'חבר שלי', 'חבר טעמים', 'HOT', 'מפתח דיסקונט', 'GiftCard max', 'Super GiftCard max', 'מועדון חדש'];
const r = P.build(labels);
assert.strictEqual(r.resolve('חבר'), 'mcc');
assert.strictEqual(r.resolve('חבר שלי'), 'mcc-sheli');
assert.strictEqual(r.resolve('חבר טעמים'), 'mcc-teamim');
assert.strictEqual(r.byId.get('mcc-sheli').parent_id, 'mcc');
assert.strictEqual(r.byId.get('mcc-teamim').parent_id, 'mcc');
assert.strictEqual(r.byId.get('max-giftcard').parent_id, 'max');
assert.strictEqual(r.byId.get('max-super-giftcard').parent_id, 'max');
assert.deepStrictEqual(Array.from(r.descendants('mcc')), ['mcc-sheli', 'mcc-teamim']);
assert(r.selectableIds.includes('mcc'));
assert(r.selectableIds.includes('mcc-sheli'));
assert(r.selectableIds.includes('mcc-teamim'));
const counts = P.aggregateCounts(r, { mcc: 784, 'mcc-sheli': 346, 'mcc-teamim': 603 });
assert.strictEqual(counts.mcc, 1733);
const unknown = r.resolve('מועדון חדש');
assert(r.byId.has(unknown));
assert.strictEqual(r.byId.get(unknown).parent_id, null);
console.log('program registry hierarchy tests passed');
